/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JCheckBox;
import javax.swing.JSpinner;
import negocio.*;
import persistencia.Conexao;
import persistencia.LogDAO;

public class Tela extends javax.swing.JFrame {

    public Tela() throws SQLException {
        initComponents();
        buttonPrato1.setSelected(true);
        buttonPrato1.setActionCommand("1");
        buttonPrato2.setActionCommand("2");
        buttonPrato3.setActionCommand("3");
        buttonPrato4.setActionCommand("4");
        buttonPrato5.setActionCommand("5");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Pratos = new javax.swing.JPanel();
        buttonPrato1 = new javax.swing.JRadioButton();
        buttonPrato2 = new javax.swing.JRadioButton();
        buttonPrato3 = new javax.swing.JRadioButton();
        buttonPrato4 = new javax.swing.JRadioButton();
        buttonPrato5 = new javax.swing.JRadioButton();
        Saladas = new javax.swing.JPanel();
        checksalada1 = new javax.swing.JCheckBox();
        checksalada4 = new javax.swing.JCheckBox();
        checksalada3 = new javax.swing.JCheckBox();
        checksalada2 = new javax.swing.JCheckBox();
        Bebidas = new javax.swing.JPanel();
        spinnerBebidas1 = new javax.swing.JSpinner();
        spinnerBebidas2 = new javax.swing.JSpinner();
        spinnerBebidas3 = new javax.swing.JSpinner();
        spinnerBebidas4 = new javax.swing.JSpinner();
        labelBebidas1 = new javax.swing.JLabel();
        labelBebidas2 = new javax.swing.JLabel();
        labelBebidas3 = new javax.swing.JLabel();
        labelBebidas4 = new javax.swing.JLabel();
        Sobremesas = new javax.swing.JPanel();
        combosobremesas = new javax.swing.JComboBox<>();
        Taxa = new javax.swing.JPanel();
        checktaxa = new javax.swing.JCheckBox();
        buttoncalcular = new javax.swing.JButton();
        buttonnovocalculo = new javax.swing.JButton();
        buttonfechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Pratos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pratos Executivos"));
        Pratos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(buttonPrato1);
        buttonPrato1.setText("Filé ao Molho Madeira");
        buttonPrato1.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(buttonPrato2);
        buttonPrato2.setText("Filé Grelhado");

        buttonGroup1.add(buttonPrato3);
        buttonPrato3.setText("Filé de Salmão Grelhado");

        buttonGroup1.add(buttonPrato4);
        buttonPrato4.setText("Bistecas Suínas Defumadas e Grelhadas");

        buttonGroup1.add(buttonPrato5);
        buttonPrato5.setText("Peito de Frango Grelhado");

        javax.swing.GroupLayout PratosLayout = new javax.swing.GroupLayout(Pratos);
        Pratos.setLayout(PratosLayout);
        PratosLayout.setHorizontalGroup(
            PratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PratosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPrato2)
                    .addComponent(buttonPrato3)
                    .addComponent(buttonPrato5)
                    .addComponent(buttonPrato1)
                    .addComponent(buttonPrato4))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PratosLayout.setVerticalGroup(
            PratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PratosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPrato1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPrato2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPrato3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPrato4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPrato5)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Saladas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Saladas"));

        checksalada1.setText("Alface");

        checksalada4.setText("Cenoura");

        checksalada3.setText("Cebola");

        checksalada2.setText("Tomate");

        javax.swing.GroupLayout SaladasLayout = new javax.swing.GroupLayout(Saladas);
        Saladas.setLayout(SaladasLayout);
        SaladasLayout.setHorizontalGroup(
            SaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaladasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(SaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checksalada1)
                    .addComponent(checksalada3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checksalada2)
                    .addComponent(checksalada4))
                .addGap(23, 23, 23))
        );
        SaladasLayout.setVerticalGroup(
            SaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaladasLayout.createSequentialGroup()
                .addGroup(SaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checksalada1)
                    .addComponent(checksalada2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checksalada3)
                    .addComponent(checksalada4))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        Bebidas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bebidas"));

        spinnerBebidas1.setToolTipText("Refrigerante 350 ml");
        spinnerBebidas1.setName("Refrigerante 350 ml"); // NOI18N

        spinnerBebidas2.setToolTipText("Refrigerante 350 ml");
        spinnerBebidas2.setName("Refrigerante 350 ml"); // NOI18N

        spinnerBebidas3.setToolTipText("Refrigerante 350 ml");
        spinnerBebidas3.setName("Refrigerante 350 ml"); // NOI18N

        spinnerBebidas4.setToolTipText("Refrigerante 350 ml");
        spinnerBebidas4.setName("Refrigerante 350 ml"); // NOI18N

        labelBebidas1.setText("Refrigerante 350 ml");

        labelBebidas2.setText("Suco natural 400 ml");

        labelBebidas3.setText("Cerveja 350 ml");

        labelBebidas4.setText("Água 500 ml");

        javax.swing.GroupLayout BebidasLayout = new javax.swing.GroupLayout(Bebidas);
        Bebidas.setLayout(BebidasLayout);
        BebidasLayout.setHorizontalGroup(
            BebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(BebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BebidasLayout.createSequentialGroup()
                        .addComponent(labelBebidas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(spinnerBebidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BebidasLayout.createSequentialGroup()
                        .addComponent(labelBebidas3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinnerBebidas3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BebidasLayout.createSequentialGroup()
                        .addComponent(labelBebidas4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinnerBebidas4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BebidasLayout.createSequentialGroup()
                        .addComponent(labelBebidas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinnerBebidas2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BebidasLayout.setVerticalGroup(
            BebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBebidas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBebidas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBebidas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBebidas2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBebidas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBebidas3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerBebidas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBebidas4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        spinnerBebidas1.getAccessibleContext().setAccessibleName("Refrigerante 350 ml");

        Sobremesas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sobremesas"));
        Sobremesas.setName("Sobremesas"); // NOI18N

        combosobremesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sorvete", "Pudim", "Torta", "Sagu" }));

        javax.swing.GroupLayout SobremesasLayout = new javax.swing.GroupLayout(Sobremesas);
        Sobremesas.setLayout(SobremesasLayout);
        SobremesasLayout.setHorizontalGroup(
            SobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SobremesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combosobremesas, 0, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        SobremesasLayout.setVerticalGroup(
            SobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SobremesasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combosobremesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Taxa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Taxa de serviço (10%)"));

        checktaxa.setText("Pagar taxa");

        javax.swing.GroupLayout TaxaLayout = new javax.swing.GroupLayout(Taxa);
        Taxa.setLayout(TaxaLayout);
        TaxaLayout.setHorizontalGroup(
            TaxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaxaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(checktaxa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TaxaLayout.setVerticalGroup(
            TaxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaxaLayout.createSequentialGroup()
                .addComponent(checktaxa)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        buttoncalcular.setText("Calcular");
        buttoncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncalcularActionPerformed(evt);
            }
        });

        buttonnovocalculo.setText("Novo Calculo");
        buttonnovocalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonnovocalculoActionPerformed(evt);
            }
        });

        buttonfechar.setText("Fechar");
        buttonfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonfecharActionPerformed(evt);
            }
        });

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        jLayeredPane1.setLayer(Pratos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Saladas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Bebidas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Sobremesas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Taxa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(buttoncalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(buttonnovocalculo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(buttonfechar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Pratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(buttoncalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonnovocalculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Taxa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Saladas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sobremesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonfechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Bebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(Saladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Sobremesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttoncalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonnovocalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Taxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonfechar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        Sobremesas.getAccessibleContext().setAccessibleDescription("Sobremesas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonfecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonfecharActionPerformed

    private void buttonnovocalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonnovocalculoActionPerformed
        this.text.setText("");
        buttoncalcular.setEnabled(true);
    }//GEN-LAST:event_buttonnovocalculoActionPerformed

    private void buttoncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncalcularActionPerformed

        Connection conexao = new Conexao().getConexao();
        Comanda comanda = new Comanda();
        String log = null;
        Prato prato = new Prato();
        Sobremesas sobremesas = new Sobremesas();
        ButtonModel m = buttonGroup1.getSelection();
        String s = null;
               
        try {
            s = m.getActionCommand();

            ResultSet resultSet = conexao.prepareStatement("SELECT * FROM pratos where id = '" + s + "'; ").executeQuery();
            while (resultSet.next()) {

                prato.setNome(resultSet.getString("descricao"));
                prato.setPreco(resultSet.getDouble("preco"));
            }
            
            comanda.setSomatorio(comanda.getSomatorio() + prato.getPreco());
            log = prato.getNome() + " " + prato.getPreco() + "  ";
            text.append(prato.getNome() + ".........................: R$" + String.format("%.2f", prato.getPreco()) + "\n");
        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

        JCheckBox[] checksaladas = {checksalada1, checksalada2, checksalada3, checksalada4};
        for (int i = 0; i < checksaladas.length; i++) {
            if (checksaladas[i].isSelected()) {
                s = checksaladas[i].getText();
                text.append(checksaladas[i].getText() + ".........................: R$1,00\n");
                comanda.setSomatorio(comanda.getSomatorio() + 1);
                log += checksaladas[i].getText() + " " + 1 + "  ";
            }
        }

        JSpinner[] spinnerbebidas = {spinnerBebidas1, spinnerBebidas2, spinnerBebidas3, spinnerBebidas4};
        for (int i = 0; i < spinnerbebidas.length; i++) {
            if ((Integer) spinnerbebidas[i].getValue() > 0) {
                try {
                    ResultSet resultSet = conexao.prepareStatement("SELECT * FROM bebida where id = '" + (i + 1) + "'; ").executeQuery();
                    while (resultSet.next()) {
                        Bebida bebida = new Bebida();
                        bebida.setPreco(resultSet.getDouble("preco"));
                        bebida.setMarca(resultSet.getString("marca"));
                        bebida.setQuantidade((Integer) spinnerbebidas[i].getValue());
                        text.append(bebida.getMarca() + ".........................: R$" + String.format("%.2f", (bebida.getPreco() * bebida.getQuantidade())) + "\n");
                        comanda.setSomatorio(comanda.getSomatorio() + (bebida.getPreco() * bebida.getQuantidade()));
                        log += bebida.getMarca() + " " + (bebida.getPreco() * bebida.getQuantidade()) + "  ";
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        try {
            s = String.valueOf(combosobremesas.getSelectedItem());
            ResultSet resultSet = conexao.prepareStatement("SELECT * FROM sobremesas where descricao = '" + s + "'; ").executeQuery();
            while (resultSet.next()) {
                sobremesas.setPreco(resultSet.getDouble("preco"));
                comanda.setSomatorio(comanda.getSomatorio() + sobremesas.getPreco());

            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        sobremesas.setNome(s);
        text.append(sobremesas.getNome() + ".........................: R$" + String.format("%.2f", sobremesas.getPreco()) + "\n");
        log += sobremesas.getNome() + " " + sobremesas.getPreco() + "  ";

        try {
            conexao.close();
        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (checktaxa.isSelected()) {
            comanda.setSomatorio(comanda.getSomatorio() * 1.1);
            log += "+ 10% - Somatório = " + String.format("%.2f", comanda.getSomatorio());
        }

        text.append("Total = " + String.format("%.2f", comanda.getSomatorio()) + "\n");
        // text.append(log);
  
        Log logsalvo = new Log(log);
        
        LogDAO logdao = new LogDAO();
        try {
            logdao.inserir(log);
        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
                
        buttoncalcular.setEnabled(false);
    }//GEN-LAST:event_buttoncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }
    private ArrayList<Comanda> comandasalva = new ArrayList();
    private ArrayList<Log> logsalvo = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bebidas;
    private javax.swing.JPanel Pratos;
    private javax.swing.JPanel Saladas;
    private javax.swing.JPanel Sobremesas;
    private javax.swing.JPanel Taxa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonPrato1;
    private javax.swing.JRadioButton buttonPrato2;
    private javax.swing.JRadioButton buttonPrato3;
    private javax.swing.JRadioButton buttonPrato4;
    private javax.swing.JRadioButton buttonPrato5;
    private javax.swing.JButton buttoncalcular;
    private javax.swing.JButton buttonfechar;
    private javax.swing.JButton buttonnovocalculo;
    private javax.swing.JCheckBox checksalada1;
    private javax.swing.JCheckBox checksalada2;
    private javax.swing.JCheckBox checksalada3;
    private javax.swing.JCheckBox checksalada4;
    private javax.swing.JCheckBox checktaxa;
    private javax.swing.JComboBox<String> combosobremesas;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBebidas1;
    private javax.swing.JLabel labelBebidas2;
    private javax.swing.JLabel labelBebidas3;
    private javax.swing.JLabel labelBebidas4;
    private javax.swing.JSpinner spinnerBebidas1;
    private javax.swing.JSpinner spinnerBebidas2;
    private javax.swing.JSpinner spinnerBebidas3;
    private javax.swing.JSpinner spinnerBebidas4;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
